version: "3"
services:
  db:
    image: postgres:latest
    container_name: local-postgres-library-author
    ports:
      - "5433:5432" # Menggunakan port 5433 di host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_author
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: local-redis-library-author
    ports:
      - "6380:6379" # Redis menggunakan port 6380 di host
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis_data:/data
